### ISSUE TITLE
Simplify widget config

### ISSUE THREAD

**Issue by MattiSG** [sgmap/ludwig#16]
I don't understand what I have to set in most of the config properties. For example, `prefix`, `apiEndpoints`…

I'd like to just give Ludwig my org/user name and repo, and be done with it. Why do I have to specify all these endpoints?

**Comment by hoshin** [comment]
I've removed all the clutter I could. Is that better / more readable now?

**Comment by MattiSG** [comment]
It's much better.

But, take this real-world config:

```js
const ludwig = new window.Ludwig({
    repoUrl: 'https://github.com/sgmap/openfisca-france/',
    template: `Précisez si ce test provient :
- [ ] d'un dossier réel
- [ ] du résultat d'une simulation sur un outil métier
`,
    prefix: 'test_',
    web: {
        acceptedTestsPath:'/tree/prod/openfisca_france/tests/mes-aides.gouv.fr',
        addPath:'/new/prod/openfisca_france/tests/mes-aides.gouv.fr',
        suggestedTestsPath:'/pulls?utf8=✓&q=is%3Apr+is%3Aopen',
    },
});
```

See how I'd like to say:

```js
const ludwig = new window.Ludwig({
    repo: 'sgmap/openfisca-france',
    branch: 'prod',
    folder: 'openfisca_france/tests/mes-aides.gouv.fr',
    template: `Précisez si ce test provient :
- [ ] d'un dossier réel
- [ ] du résultat d'une simulation sur un outil métier
`,
    prefix: 'test_',
});
```

?

As a client, I know my repo, my target branch and folder. Don't make me think about what are the GitHub paths.

**Comment by hoshin** [comment]
PR #26 should simplify widget configuration even more. No more "not that useful" paths anyhow.
