### ISSUE TITLE
Document commitReferenceToBranchFrom

### ISSUE THREAD

**Issue by MattiSG** [sgmap/ludwig#18]
What is this? If I am supposed to always branch from a given commit, this is never going to work. I want to branch from `master`, not from one specific commit. I would have to update all the time.

**Comment by hoshin** [comment]
PR #25 should allow to always get the most recent ref for master

**Comment by MattiSG** [comment]
Didn't test yet, but replacing `commitReferenceToBranchFrom` by `branchToCreatePullRequestsFor` is enough for this specific issue to be closed.
