### ISSUE TITLE
Inconsistent documentation

### ISSUE THREAD

**Issue by MattiSG** [sgmap/ludwig#19]
> Note : Cette configuration est packagée avec le widget à distribuer, il est inutile de la charger à part.

Ou bien

>  pour accéder aux fonctionnalités, il faut donc l'instancier en passant par un new Ludwig(configuration)

?

**Comment by hoshin** [comment]
Inconsistencies should be gone now

**Comment by MattiSG** [comment]
:+1:

Pourquoi avoir documenté l'API du widget dans un [doc à part](https://github.com/sgmap/ludwig/blob/master/documentation/widgetAPI.md) ?

**Comment by hoshin** [comment]
C'est un test, je voulais essayer de voir si le readme ne serait pas un peu plus lisible et "activable" en enlevant les sections peut être un peu moins nécessaires au tout départ (sachant que dans le readme il y a tout de même les premières infos pour démarrer)
