### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by MattiSG** [sgmap/ludwig#2]
```
npm WARN Ludwig-API@0.0.0 No license field.
```

https://github.com/sgmap/bonnes-pratiques#licence

**Comment by hoshin** [comment]
Should be ok by now

**Comment by MattiSG** [comment]
Please close issues when they're done  ;)

**Comment by MattiSG** [comment]
(best: open a pull request referencing the issue)

**Comment by hoshin** [comment]
For lack of a PR, here's the commit ref : https://github.com/sgmap/ludwig/commit/f1fa0828fd873da2bf58de3cd00a0273d880b112
