### ISSUE TITLE
Add repo metadata

### ISSUE THREAD

**Issue by MattiSG** [sgmap/ludwig#3]
`npm WARN Ludwig-API@0.0.0 No repository field.`

**Comment by hoshin** [comment]
Should be fixed now

**Comment by hoshin** [comment]
For lack of a PR, here's the commit ref : https://github.com/sgmap/ludwig/commit/3f92f468d17ac0394bcebd38baea676434bf81d2

**Comment by MattiSG** [comment]
:+1:  :smiley:
