### ISSUE TITLE
How am I supposed to use `generateLudwigSuggestionEndpointURL`?

### ISSUE THREAD

**Issue by MattiSG** [sgmap/ludwig#37]
From the doc and exploration, it looks like `generateLudwigSuggestionEndpointURL` still depends on a `GET` query. Therefore, the only limitation that is removed is the URL length handled by GitHub (#23), but not the limitation from browsers.
For this feature to make sense, I need to be able to use `POST` (or any other HTTP method that supports sending a body of arbitrary length).

This API seems to make more sense with a JSON endpoint exposed by the server, that takes in an object with `title`, `description` and `contents`.

**Comment by hoshin** [comment]
This has been fixed in #56
