### ISSUE TITLE
Test page doesn't serve ludwig.js

### ISSUE THREAD

**Issue by MattiSG** [sgmap/ludwig#38]
`http://localhost:3000/ludwig.js` is not `GET`table, leading `http://localhost:3000/test` to be non-functional.

**Comment by hoshin** [comment]
It seems to work on my end (GH master head works fine, last published version tag works too), how do you reproduce this?

**Comment by MattiSG** [comment]
```
npm start
open localhost:3000/test
```
![capture d ecran 2016-04-14 a 14 59 41](https://cloud.githubusercontent.com/assets/222463/14528785/8c6a2292-0251-11e6-87e8-eba9ab733f83.png)

**Comment by hoshin** [comment]
Closing as it seems to work fine right now on master (and if I remember well we discussed this a while back?)
