### ISSUE TITLE
Add ESlint

### ISSUE THREAD

**Issue by MattiSG** [sgmap/ludwig#5]
There are many style inconsistencies, especially on whitespace. Please add [ESlint](eslint.org).

Example [`eslintrc`](https://github.com/sgmap/cout-embauche/blob/gh-pages/.eslintrc).

**Comment by MattiSG** [comment]
Oh ok, I see you have `jshint`. If you prefer to keep that tool, please set it up to have consistent style, especially on whitespace and colon-spacing  :)

**Comment by hoshin** [comment]
I don't have a particular "religion" on linting tools so ESlint is fine with me : #11

**Comment by hoshin** [comment]
Done & pushed to master juste now (https://github.com/sgmap/ludwig/commit/fca5a4cc08e1ac900791269283ebf50316bc29e8)
