### ISSUE TITLE
Compile ES6

### ISSUE THREAD

**Issue by MattiSG** [sgmap/ludwig#6]
The generated `bundle.js` still has `let`, template strings and other ES6 features. It won't load in my browser.

[Example Webpack config](https://github.com/sgmap/mes-aides-ui/blob/rewrite/webpack.config.js#L21-L29).

**Comment by hoshin** [comment]
Webpack configuration updated to allow ES6 features in https://github.com/sgmap/ludwig/commit/e1fc0022431f1b76fe0b3f9ce18b4507dabca0d5. There should not be issues loading the widget anymore (at least not ES6 related)
