### ISSUE TITLE
Is the Node engine constraint really necessary?

### ISSUE THREAD

**Issue by MattiSG** [sgmap/ludwig#7]
Your `package.json` states:

```json
"engines": {
    "node": "^5.3.0"
},
```

This is a very strong constraint, especially since v5 is not an LTS. Are you sure it is needed?

**Comment by hoshin** [comment]
Indeed that's a bit strong... Not sure why I ended up writing this. There is no particular reason atm so that constraint can probably be lifted

**Comment by hoshin** [comment]
PR : #10

**Comment by hoshin** [comment]
Merged, closing issue
