### ISSUE TITLE
Use a single config file

### ISSUE THREAD

**Issue by MattiSG** [sgmap/ludwig#8]
I see duplication between the widget and the backend config files. Is there any strong reason for not using the same config file with shared properties?

**Comment by hoshin** [comment]
Well, we probably don't want to have our API keys bundled with the widget (that's the main reason I see for the duplication) and keep those on the server side. Apart from that, there is indeed no reason that I can think of.

**Comment by MattiSG** [comment]
Use an NPM config key or env variable for secrets. They should not be in a shared config file anyway  :wink:

**Comment by hoshin** [comment]
Well they definitely should not indeed (hence the actual, kinda sub-optimal, duplication).
We might as well switch to env variables, this should make our lives easier =)

**Comment by MattiSG** [comment]
I'd favour NPM config keys as they give actionable defaults. We can discus this, but if you go the env vars way, please add some kind of `.env` fie.

**Comment by hoshin** [comment]
I merged a bit too fast maybe but here's what has been done so far #12

**Comment by MattiSG** [comment]
Seems to be done…?

**Comment by hoshin** [comment]
It is indeed, closing
